{% set version = "1.4.0" %}

package:
  name: tblib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tblib/tblib-{{ version }}.tar.gz
  sha256: bd1ad564564a158ff62c290687f3db446038f9ac11a0bf6892712e3601af3bcd

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - tblib

about:
  home: https://github.com/ionelmc/python-tblib
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Traceback serialization library.'
  description: |
    tblib allows you to Pickle tracebacks and raise exceptions with pickled
    tracebacks in different processes.This allows better error handling when
    running code over multiple processes.
  dev_url: https://github.com/ionelmc/python-tblib
  doc_url: https://python-tblib.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ionelmc/python-tblib/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - pmlandwehr
