travis:
  secure:
    BINSTAR_TOKEN: jSN4TBudwAOH40tdAgVJ3718tiy8SQ335IeSblBY90iClDACJmyTeVmihbff1lyNrhyW0ZUtrdJWyVs5MuTZ/LxjcH7Q3tdi56HIeHn97Pyi2K3fAVEfTc/+m6NwKJ17LBZWoq7J1tiMxdS2IInGhJdCxad4D8vWrfjuVwGPuQhGS+8EygXd/THQlTbQHUR3OzV+KRFISJ3PgVrvCXF5CTDobu61Z8eRCzrT5QgeoMH+zt6EZw9axVD4d8hBSjvE41jEOTVf0y46cyrGbV+1akahBf8yVQqT2INnQXMZsvnc7IX9VqbvYi7nJEhVdPVjXJvHM8G90QAETuqAEmFgrCGTZhDvPTxPUie+sDwG5xnYQ15tjXHHAAXira8hRH1Jy2RUqwm25J2fpAap5LB3z+Hc1xDGMSuRJ4InzYU0oP9gw97aphD7o3fE3Zw+z2laMjq8/9o9qV8PMPPdsUtcAZ0uk8zhmkGC7XaW8X/dunDNlDK7Nf4rdzx0RzY5HgCGULhsh8CWsdHmpCvJXqsLI+vcsEWWDwj7pvnGohQkemBB9VKWc9wZgHdxNEbJ+YBhvUuYG2zMlZGaxzKBI/Xy6xzmTp+QP17JKc+3ktWg5HsIDhLFmYt86mWLdZUKhCwzBkDumpVoWxiGj4Zqv+cTLZbCSOIUhbV0eS1nwTsqKLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
